### ISSUE TITLE
Resource not accessible by integration

### ISSUE THREAD

**Issue by DefinetlyNotAI** [actions-cool/issues-similarity-analysis#8]
Run actions-cool/issues-similarity-analysis@v1
[Action][filter-issues][length: 2]
Error: Resource not accessible by integration

```yaml
name: Issues Similarity Analysis

on:
  issues:
    types: [opened, edited]

jobs:
  similarity-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: analysis
        uses: actions-cool/issues-similarity-analysis@v1
        with:
          filter-threshold: 0.5
          title-excludes: '(exclude), (ignore), WIP'
          comment-title: '## Issues Similarity Analysis:'
          comment-body: '${index}. ${similarity} #${number}'
          # comment-body: '[#${number}][${title}][${similarity}]'
```
